<%@page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>
<div id="fv-notifications" class="fv-notifications" hidden>
  <button id="fv-notification-toggle" type="button" aria-label="Notifications" aria-expanded="false"><i class="bi bi-bell-fill"></i><span id="fv-notification-count" hidden></span></button>
  <section id="fv-notification-panel" hidden><header><strong>Notifications</strong><button id="fv-mark-all-read" type="button">Mark all read</button></header><div id="fv-notification-list"></div></section>
</div>
<style>
.fv-notifications{position:relative!important;display:flex!important;align-items:center!important;margin-left:10px;z-index:1001}.fv-notification-toggle{position:relative!important;display:grid!important;place-items:center!important;width:42px!important;height:42px!important;padding:0!important;border:0!important;border-radius:10px!important;background:#e0f2fe!important;color:#0284c7!important;font-size:20px!important;line-height:1!important;box-shadow:none!important;transition:background .2s ease,transform .2s ease}.fv-notification-toggle:hover{background:#bae6fd!important;transform:translateY(-1px)}#fv-notification-count{position:absolute;top:-7px;right:-9px;min-width:22px;height:18px;padding:1px 5px;border:2px solid #fff;border-radius:10px;background:#0284c7;color:#fff;font-size:10px;font-weight:800;line-height:14px}#fv-notification-panel{position:absolute;right:0;top:54px;width:440px;max-width:calc(100vw - 24px);background:#fff;border:1px solid #e2e8f0;border-radius:18px;box-shadow:0 20px 48px rgba(15,23,42,.18);overflow:hidden}#fv-notification-panel header{display:flex;justify-content:space-between;align-items:center;padding:18px 20px;border-bottom:1px solid #e5e7eb}#fv-mark-all-read{border:0;background:none;color:#0284c7;font-size:13px;font-weight:700}#fv-notification-list{max-height:460px;overflow-y:auto}.fv-notification-item{display:block;width:100%;padding:17px 20px;border:0;border-bottom:1px solid #f1f5f9;background:#fff;text-align:left;cursor:pointer}.fv-notification-item:hover{background:#f0f9ff}.fv-notification-item.unread{background:#f8fafc}.fv-notification-title,.fv-notification-message,.fv-notification-time{display:block}.fv-notification-title{color:#111827;font-size:15px;font-weight:700}.fv-notification-message{margin-top:4px;color:#64748b;font-size:13px;line-height:1.5}.fv-notification-time{margin-top:7px;color:#94a3b8;font-size:12px}.fv-notification-empty{padding:36px 20px;color:#64748b;text-align:center;font-size:15px}@media(max-width:768px){.fv-notifications{margin-left:6px}#fv-notification-panel{right:-8px;width:calc(100vw - 24px)}}
</style>
<script>
(function(){const root=document.getElementById('fv-notifications'),toggle=document.getElementById('fv-notification-toggle'),panel=document.getElementById('fv-notification-panel'),count=document.getElementById('fv-notification-count'),list=document.getElementById('fv-notification-list'),markAll=document.getElementById('fv-mark-all-read'),contextPath='<%= request.getContextPath() %>';const navTarget=document.querySelector('.navbar-nav')||document.querySelector('.topbar .container > div:last-child');if(navTarget)navTarget.appendChild(root);function closePanel(){panel.hidden=true;toggle.setAttribute('aria-expanded','false');}function updateCount(value){count.hidden=value===0;count.textContent=value>99?'99+':value;}async function load(){try{const response=await fetch(contextPath+'/notifications',{cache:'no-store'});if(!response.ok)return;const data=await response.json();root.hidden=false;updateCount(data.unreadCount||0);list.replaceChildren();if(!data.notifications.length){list.innerHTML='<div class="fv-notification-empty">You are all caught up.</div>';return;}data.notifications.forEach(function(notification){const item=document.createElement('button');item.type='button';item.className='fv-notification-item'+(notification.read?'':' unread');const title=document.createElement('span'),message=document.createElement('span'),time=document.createElement('span');title.className='fv-notification-title';message.className='fv-notification-message';time.className='fv-notification-time';title.textContent=notification.title;message.textContent=notification.message;time.textContent=new Date(notification.createdAt).toLocaleString();item.append(title,message,time);item.addEventListener('click',async function(){closePanel();await fetch(contextPath+'/markNotificationRead?id='+encodeURIComponent(notification.id),{method:'POST'});if(notification.orderId)window.location.href=contextPath+'/trackOrder.jsp?orderId='+encodeURIComponent(notification.orderId);else load();});list.appendChild(item);});}catch(error){}}toggle.addEventListener('click',function(){panel.hidden=!panel.hidden;toggle.setAttribute('aria-expanded',String(!panel.hidden));});markAll.addEventListener('click',async function(){closePanel();await fetch(contextPath+'/markAllNotifications',{method:'POST'});load();});document.addEventListener('click',function(event){if(!root.contains(event.target))closePanel();});load();window.setInterval(load,30000);})();
</script>
