package com.food_application.DAOApplication;
import java.sql.*; import java.util.*;
import com.food_application.DAO.NotificationDAO; import com.food_application.model.Notification; import com.food_application.utility.DBConnection;
public class NotificationDAOImpl implements NotificationDAO {
 private final Connection con;
 public NotificationDAOImpl(){con=DBConnection.getConnection(); ensureTable();}
 private void ensureTable(){try(Statement s=con.createStatement()){s.executeUpdate("CREATE TABLE IF NOT EXISTS notifications (notification_id INT AUTO_INCREMENT PRIMARY KEY, customer_id INT NOT NULL, order_id INT NULL, title VARCHAR(150), message VARCHAR(500), notification_type VARCHAR(50), is_read BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_notification_customer (customer_id, created_at))");}catch(Exception e){e.printStackTrace();}}
 public void addNotification(Notification n){String q="INSERT INTO notifications(customer_id,order_id,title,message,notification_type,is_read) VALUES(?,?,?,?,?,false)";try(PreparedStatement p=con.prepareStatement(q)){p.setInt(1,n.getCustomerId());if(n.getOrderId()==null)p.setNull(2,Types.INTEGER);else p.setInt(2,n.getOrderId());p.setString(3,n.getTitle());p.setString(4,n.getMessage());p.setString(5,n.getNotificationType());p.executeUpdate();}catch(Exception e){e.printStackTrace();}}
 public List<Notification> getCustomerNotifications(int c,int o,int l){List<Notification> list=new ArrayList<>();String q="SELECT * FROM notifications WHERE customer_id=? ORDER BY created_at DESC,notification_id DESC LIMIT ? OFFSET ?";try(PreparedStatement p=con.prepareStatement(q)){p.setInt(1,c);p.setInt(2,l);p.setInt(3,o);try(ResultSet r=p.executeQuery()){while(r.next()){Notification n=new Notification();n.setNotificationId(r.getInt("notification_id"));n.setCustomerId(c);int id=r.getInt("order_id");n.setOrderId(r.wasNull()?null:id);n.setTitle(r.getString("title"));n.setMessage(r.getString("message"));n.setNotificationType(r.getString("notification_type"));n.setRead(r.getBoolean("is_read"));n.setCreatedAt(r.getTimestamp("created_at"));list.add(n);}}}catch(Exception e){e.printStackTrace();}return list;}
 public int getUnreadCount(int c){try(PreparedStatement p=con.prepareStatement("SELECT COUNT(*) FROM notifications WHERE customer_id=? AND is_read=false")){p.setInt(1,c);try(ResultSet r=p.executeQuery()){return r.next()?r.getInt(1):0;}}catch(Exception e){e.printStackTrace();}return 0;}
 public void markAsRead(int id,int c){run("UPDATE notifications SET is_read=true WHERE notification_id=? AND customer_id=?",id,c);} public void markAllAsRead(int c){try(PreparedStatement p=con.prepareStatement("UPDATE notifications SET is_read=true WHERE customer_id=?")){p.setInt(1,c);p.executeUpdate();}catch(Exception e){e.printStackTrace();}} public void deleteNotification(int id,int c){run("DELETE FROM notifications WHERE notification_id=? AND customer_id=?",id,c);} public void deleteAllNotifications(int c){try(PreparedStatement p=con.prepareStatement("DELETE FROM notifications WHERE customer_id=?")){p.setInt(1,c);p.executeUpdate();}catch(Exception e){e.printStackTrace();}}
 private void run(String q,int id,int c){try(PreparedStatement p=con.prepareStatement(q)){p.setInt(1,id);p.setInt(2,c);p.executeUpdate();}catch(Exception e){e.printStackTrace();}}
}
